# Generated by Django 3.1.4 on 2020-12-31 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('favoriteCharacters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecharacters',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoritecharacters',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
