# Generated by Django 3.1.4 on 2020-12-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favoriteCharacters', '0002_auto_20201231_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecharacters',
            name='id',
        ),
        migrations.AlterField(
            model_name='favoritecharacters',
            name='user_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
